import type { Metadata } from "next";
import "../../globals.css";
import ProfileSidebar from "./_components/ProfileSidebar";
import { Satoshi } from "@/lib/fonts";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Satoshi.variable}`}
      >
        <div className="flex w-full px-8 gap-8 ">
          <ProfileSidebar />
        <div className="w-full">
          {children}
        </div>
        </div>
      </body>
    </html>
  );
}
