import type { Metadata } from "next";
import "../..//globals.css";
import ProfileSidebar from "./_components/ProfileSidebar";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={``}
      >
        <div className="flex w-full ">
          <ProfileSidebar />
        <div className="w-full">
          {children}
        </div>
        </div>
      </body>
    </html>
  );
}
