import type { Metadata } from "next";
import "../globals.css";
import LayoutSidebar from "@/components/shared/dashboard/LayoutSidebar";
import LayoutNavbar from "@/components/shared/dashboard/LayoutNavbar";
import { Satoshi } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`${Satoshi.variable} antialiased`}>
        <div className="flex h-screen w-full overflow-hidden">
          {/* Sidebar fixe */}
          <LayoutSidebar />
          
          {/* Contenu principal */}
          <div className="flex flex-1 flex-col overflow-hidden">
            {/* Navbar fixe */}
            <LayoutNavbar />
            
            {/* Zone de contenu scrollable */}
            <main className="flex-1 overflow-y-auto bg-gray-50">
              <div className="container mx-auto px-4 py-8">
                {children}
              </div>
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}